import { Wallet, Ticket } from "lucide-react";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { CopyButton } from "@/components/shared/CopyButton";
import { LoadingState } from "@/components/shared/LoadingState";
import { EmptyState } from "@/components/shared/EmptyState";
import { ErrorState } from "@/components/shared/ErrorState";
import { formatCurrency, formatDate } from "@/lib/format-utils";
import { cn } from "@/lib/utils";
import { useUserCreditQuery } from "../api/user-queries";
import type { CreditLedgerEntry } from "../api/user-api";

interface UserCreditTabProps {
  userId: string;
}

/** Human labels for the append-only credit ledger entry types. */
const LEDGER_LABELS: Record<CreditLedgerEntry["entryType"], string> = {
  REFERRAL_BONUS: "Referral bonus",
  REFERRER_REWARD: "Referrer reward",
  REDEMPTION: "Redeemed to discount",
  REFUND: "Refund",
  ADJUSTMENT: "Manual adjustment",
  CLAWBACK: "Clawback",
};

export function UserCreditTab({ userId }: UserCreditTabProps) {
  const { data, isLoading, isError, refetch } = useUserCreditQuery(userId);

  if (isLoading) {
    return <LoadingState variant="card" />;
  }

  if (isError || !data) {
    return (
      <ErrorState
        title="Couldn't load credit"
        message="The user's credit wallet failed to load."
        onRetry={() => void refetch()}
      />
    );
  }

  const { balance, ledger, redemptions } = data;

  return (
    <div className="space-y-8">
      {/* Balance headline */}
      <section className="rounded-lg border p-5">
        <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
          STREET credit balance
        </p>
        <p className="mt-1 text-3xl font-semibold tabular-nums">
          {formatCurrency(balance)}
        </p>
      </section>

      {/* Credit ledger */}
      <section>
        <h2 className="text-base font-semibold leading-none">Credit ledger</h2>
        {ledger.length === 0 ? (
          <div className="mt-4 border-t pt-5">
            <EmptyState
              icon={Wallet}
              title="No credit activity"
              description="This user hasn't earned or spent any credit yet."
            />
          </div>
        ) : (
          <ul className="mt-4 divide-y border-t">
            {ledger.map((entry) => (
              <li
                key={entry.id}
                className="flex items-center justify-between gap-4 py-3"
              >
                <div className="min-w-0">
                  <p className="text-sm font-medium">
                    {LEDGER_LABELS[entry.entryType]}
                  </p>
                  <p className="truncate text-xs text-muted-foreground">
                    {entry.description ?? "—"} · {formatDate(entry.createdAt)}
                  </p>
                </div>
                <span
                  className={cn(
                    "shrink-0 text-sm font-semibold tabular-nums",
                    entry.amount < 0
                      ? "text-rose-600 dark:text-rose-400"
                      : "text-emerald-600 dark:text-emerald-400",
                  )}
                >
                  {entry.amount < 0 ? "−" : "+"}
                  {formatCurrency(Math.abs(entry.amount))}
                </span>
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Generated discount codes */}
      <section>
        <div className="space-y-1">
          <h2 className="text-base font-semibold leading-none">
            Discount codes
          </h2>
          <p className="text-xs text-muted-foreground">
            Codes generated by redeeming credit
          </p>
        </div>
        {redemptions.length === 0 ? (
          <div className="mt-4 border-t pt-5">
            <EmptyState
              icon={Ticket}
              title="No discount codes"
              description="This user hasn't redeemed any credit into a discount code."
            />
          </div>
        ) : (
          <ul className="mt-4 divide-y border-t">
            {redemptions.map((code) => (
              <li
                key={code.id}
                className="flex items-center justify-between gap-4 py-3"
              >
                <div className="min-w-0 space-y-1">
                  <div className="flex items-center gap-1.5">
                    <span className="font-mono text-sm font-medium">
                      {code.discountCode}
                    </span>
                    <CopyButton value={code.discountCode} label="Copy code" />
                  </div>
                  <p className="truncate text-xs text-muted-foreground">
                    {formatCurrency(code.amount)} off · min{" "}
                    {formatCurrency(code.minimumOrderAmount)}
                    {code.expiresAt ? ` · exp ${formatDate(code.expiresAt)}` : ""}
                  </p>
                </div>
                <StatusBadge status={code.status} size="sm" />
              </li>
            ))}
          </ul>
        )}
      </section>
    </div>
  );
}
