import { api, toQueryString } from "@/lib/api-client";
import type { PaginatedResponse } from "@/types";
import type {
  BackendUser,
  BackendUserAddress,
  BackendUserDevice,
  BackendUserOrder,
} from "../types";

// ---------------------------------------------------------------------------
// Request params
// ---------------------------------------------------------------------------

/** Derived account status filter (matches deriveUserStatus). */
export type UserStatusFilter = "active" | "suspended" | "blocked";

export interface GetUsersParams {
  search?: string;
  /** Server-side derived status filter. */
  status?: UserStatusFilter;
  /** Backend allowlist: name | email | phone | createdAt */
  sortBy?: string;
  sortOrder?: "asc" | "desc";
  page?: number;
  limit?: number;
}

// ---------------------------------------------------------------------------
// API functions
// ---------------------------------------------------------------------------

/** Fetch a paginated list of users. */
export function getUsers(
  params: GetUsersParams = {},
): Promise<PaginatedResponse<BackendUser>> {
  return api.getPaginated<BackendUser>(`admin/users${toQueryString(params)}`);
}

/** Fetch a single user by ID. */
export async function getUser(userId: string): Promise<BackendUser> {
  return api.get<BackendUser>(`admin/users/${userId}`);
}

/** Fetch addresses for a user. */
export async function getUserAddresses(
  userId: string,
): Promise<BackendUserAddress[]> {
  return api.get<BackendUserAddress[]>(`admin/users/${userId}/addresses`);
}

/** Payload for PATCH /admin/users/:userId/addresses/:addressId. */
export interface UpdateUserAddressPayload {
  label?: string;
  line1?: string;
  line2?: string;
  city?: string;
  postcode?: string;
  country?: string;
  deliveryInstructions?: string;
}

/** Update a user address (partial update). */
export function updateUserAddress(
  userId: string,
  addressId: string,
  data: UpdateUserAddressPayload,
): Promise<BackendUserAddress> {
  return api.patch<BackendUserAddress>(
    `admin/users/${userId}/addresses/${addressId}`,
    data,
  );
}

/** Raw order shape from backend (nested vendor relation, string amounts). */
interface RawUserOrder {
  id: string;
  orderId: string;
  status: string;
  totalAmount: string | number | null;
  vendorId?: string;
  vendor?: { id: string; storeName?: string };
  createdAt: string;
  updatedAt: string;
  [key: string]: unknown;
}

/**
 * Fetch a page of a user's orders. Flattens the vendor relation.
 *
 * Page and limit are explicit: the endpoint defaults to limit=10, so omitting
 * them silently returned the 10 most recent orders and the tab rendered them
 * as if that were everything (TT-445).
 */
export async function getUserOrders(
  userId: string,
  params: { page?: number; limit?: number } = {},
): Promise<PaginatedResponse<BackendUserOrder>> {
  const { data, meta } = await api.getPaginated<RawUserOrder>(
    `admin/users/${userId}/orders${toQueryString(params)}`,
  );
  const orders = data.map((raw) => ({
    id: raw.id,
    orderNumber: raw.orderId ?? null,
    status: raw.status,
    totalAmount: raw.totalAmount != null ? Number(raw.totalAmount) : null,
    currency: null,
    retailerId: raw.vendor?.id ?? raw.vendorId ?? null,
    retailerName: raw.vendor?.storeName ?? null,
    createdAt: raw.createdAt,
    updatedAt: raw.updatedAt,
  }));
  return { data: orders, meta };
}

/** Fetch devices for a user. */
export async function getUserDevices(
  userId: string,
): Promise<BackendUserDevice[]> {
  return api.get<BackendUserDevice[]>(`admin/users/${userId}/devices`);
}

// ---------------------------------------------------------------------------
// User stats
// ---------------------------------------------------------------------------

export interface UserStats {
  totalOrders: number;
  totalSpent: string;
  firstOrderDate: string | null;
  lastOrderDate: string | null;
}

/** Fetch order stats for a user. */
export async function getUserStats(userId: string): Promise<UserStats> {
  return api.get<UserStats>(`admin/users/${userId}/stats`);
}

// ---------------------------------------------------------------------------
// Credit wallet
// ---------------------------------------------------------------------------

/** Append-only credit ledger entry. Positive = credit, negative = debit. */
export interface CreditLedgerEntry {
  id: string;
  amount: number;
  entryType:
    | "REFERRAL_BONUS"
    | "REFERRER_REWARD"
    | "REDEMPTION"
    | "REFUND"
    | "ADJUSTMENT"
    | "CLAWBACK";
  description: string | null;
  referenceType: string | null;
  createdAt: string;
}

/** A discount code the user generated by redeeming credit. */
export interface UserDiscountCode {
  id: string;
  discountCode: string;
  amount: number;
  status: "PENDING" | "COMPLETED" | "FAILED" | "USED" | "EXPIRED";
  minimumOrderAmount: number;
  shopDomain: string;
  usedOnShopifyOrderId: string | null;
  expiresAt: string | null;
  createdAt: string;
}

export interface UserCredit {
  balance: number;
  ledger: CreditLedgerEntry[];
  redemptions: UserDiscountCode[];
}

/** Fetch a user's credit wallet: balance, ledger, and generated discount codes. */
export async function getUserCredit(userId: string): Promise<UserCredit> {
  return api.get<UserCredit>(`admin/users/${userId}/credit`);
}

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/** Payload for PATCH /admin/users/:id. */
export interface UpdateUserPayload {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  language?: string;
}

/** Update a user by ID (partial update). */
export async function updateUser(
  userId: string,
  data: Partial<UpdateUserPayload>,
): Promise<BackendUser> {
  return api.patch<BackendUser>(`admin/users/${userId}`, data);
}
